[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "nodejs", "poppler_utils", "tesseract"]

[phases.install]
cmds = [
    "npm ci",
    "python3 -m venv .venv",
    ". .venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = []  # Clear default build commands to prevent automatic "pip install"

[start]
cmd = ". .venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
